### ISSUE TITLE
How many GPU memory need for generate a full scene mesh video like [demo_kitti00.mp4 ] ?

### ISSUE THREAD

**Issue by qpc001** [PRBonn/PIN_SLAM#2]
How to setup config file?

**Comment by YuePanEdward** [comment]
Hi, thanks for your interest in our project.
We tested on a GPU with 16 GB memory.  You may use the config file such as `./config/lidar_slam/run_kitti.yaml`
To run a GPU with fewer than 8 GB of memory, you may consider the following changes in the config file:
```
continual:
  pool_capacity: 5e6   # decrease 
optimizer:
  batch_size: 8192      # decrease
```

And decrease the voxel hashing buffer size here:
https://github.com/PRBonn/PIN_SLAM/blob/5e8d4a6a2656391df43ea4e33f200e218838d58f/utils/config.py#L109
