### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by whwh747** [PRBonn/PIN_SLAM#29]
Thank you for your excellent work. I would like to ask if the variable `mesh_freq_frame` means that the mesh is rebuilt every `mesh_freq_frame` frames? How does this differ from reading the dataset every `mesh_freq_frame` frames?

**Comment by whwh747** [comment]
thank you，
I saw the range input command. I used run_ncd.yaml, added pc_path, and commented out pose_path. I encountered a track lost issue (I used range 0 1300 5).

**Comment by YuePanEdward** [comment]
Yes, as I mentioned, PIN-SLAM would lose track when processing with large frame intervals.
There are two options:
1. Instead of loading data with skipped frames by setting `--range x xxx xx`, you may try to add in the config file:
```
optimizer: # mappers 
   mapping_freq_frame: 5
```
This will then let PIN-SLAM do the mapping (SDF fitting) once per `mapping_freq_frame`. In this case, the tracking results would be worse (with not up-to-date and map underfitting) but may not lose track.

2. Use the pure mapping mode (with known poses)
You can then specify the path to the referenced pose `pose_path` in the config file and comment out the tracking part.
An example would be like:
```
setting:
  name: "test_ncd_128_easy"
  output_root: "./experiments"
  pc_path: "./data/ncd_128/quad_e/ply"
  pose_path: "./data/ncd_128/quad_e/poses.txt" 
  deskew: True
process:
  ...
continual:
  ...
# tracker:
#  source_vox_down_m: 0.6
#  iter_n: 100
#  valid_nn_k: 5
pgo:
 ...
eval:
 ...
```
I hope this can help you resolve your problem.
